[package]
name = "fetcher"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
dto = { workspace = true, features = ["server"] }
serde.workspace = true
serde_json.workspace = true
by-axum.workspace = true

tokio = { version = "1.40.0", features = ["full"] }
tower = "0.5.1"
chrono = "0.4.39"
reqwest.workspace = true
rest-api = "0.1.1"
by-types.workspace = true
sqlx.workspace = true
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
validator = "0.20.0"
schemars = "0.8.21"

alloy = { version = "0.11.1", features = ["provider-ws"] }
futures-util = "0.3.31"
