
name: PR Testing

on:
  pull_request:
      types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  main-ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          target: wasm32-unknown-unknown
          toolchain: stable

      - uses: cargo-bins/cargo-binstall@main

      - name: Install dioxus-cli
        run: |
          cargo binstall dioxus-cli --force
          cargo binstall toml-cli --force

      - name: Checking violate
        env:
          REGION: ap-northeast-2
          SERVICE: main-ui
        run: |
          dx check -p $SERVICE

      - name: Deploy APIs
        env:
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ""
          SECRET_ACCESS_KEY: ""
          FIREBASE_API_KEY: ""
          FIREBASE_AUTH_DOMAIN: ""
          FIREBASE_PROJECT_ID: ""
          FIREBASE_STORAGE_BUCKET: ""
          FIREBASE_MESSAGING_SENDER_ID: ""
          FIREBASE_APP_ID: ""
          FIREBASE_MEASUREMENT_ID: ""
          MAIN_API_ENDPOINT: ""
          ENV: dev
          SERVICE: main-ui
          DOMAIN: incheonheroes.world
          KAKAO_CLIENT_ID: ""
          KAKAO_REDIRECT_URI: ""
        run: |
          npm i -g aws-cdk @tailwindcss/cli
          make build

  main-api:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          target: wasm32-unknown-unknown
          toolchain: stable

      - uses: cargo-bins/cargo-binstall@main

      - name: Deploy APIs
        env:
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ""
          SECRET_ACCESS_KEY: ""
          BASE_DOMAIN: dev.incheonheroes.world
          ENV: dev
          RUST_LOG: debug
          SERVICE: main-api
          DOMAIN: api.dev.incheonheroes.world
          JWT_SECRET_KEY: ""

          DATABASE_TYPE: postgres
          DATABASE_URL: ""

          KLAYTN_FEEPAYER_KEY: ""
          KLAYTN_FEEPAYER_ADDR: ""
          KLAYTN_OWNER_KEY: ""
          KLAYTN_OWNER_ADDR: ""
          KLAYTN_ENDPOINT: ""
          CONTRACT_INCHEON_CONTENTS: ""
        run: |
          npm i -g aws-cdk
          make build
